### ISSUE TITLE
赞一个

### ISSUE THREAD

**Issue by zheroic** [ZzXxL1994/Movie_Recommend#17]
val jdbcURL = "jdbc:mysql://movie2:3306/recommend?useUnicode=true&characterEncoding=utf-8"
  val alsTable = "recommend.alsTab"
  val recResultTable = "recommend.similarTab"
  val top5Table = "recommend.top5Result"
  val userTable= "recommend.user"
  val ratingTable= "recommend.rating"

在附件sql中只看到movie的sql没看到这几个

**Comment by zheroic** [comment]
> val jdbcURL = "jdbc:mysql://movie2:3306/recommend?useUnicode=true&characterEncoding=utf-8"
> val alsTable = "recommend.alsTab"
> val recResultTable = "recommend.similarTab"
> val top5Table = "recommend.top5Result"
> val userTable= "recommend.user"
> val ratingTable= "recommend.rating"
> 
> 在附件sql中只看到movie的sql没看到这几个

**Comment by jinzhuoyi** [comment]
你好，我是fork这个人的https://github.com/LuckyZXL2016/Movie_Recommend，自己也没有跑通呢，后来不做这个了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 下午4:24
收件人:&nbsp;"LuckyZXL2016/Movie_Recommend"<Movie_Recommend@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [LuckyZXL2016/Movie_Recommend] 你好 我想请问一下这个sql在哪 (#17)





 
Closed #17.
